# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Create requirements.txt

on:
  workflow_dispatch:
  push:
    paths:
      - pyproject.yaml


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.1.2

    - name: Create requirements.txt
      run: |
        poetry export -f requirements.txt --output requirements.txt

    - name: Push
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit --allow-empty -m "CI auto build"
        git push
